"""baseline: full ARIA schema

Revision ID: 7c8da978d3a4
Revises: 
Create Date: 2026-08-16 22:09:19.665633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders ARIA's pgvector column as src.models.EmbeddingColumn().
import src.models  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '7c8da978d3a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_requests_status'), 'action_requests', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_request_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action_request_id'), 'audit_events', ['action_request_id'], unique=False)
    op.create_table('autonomy_state',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('emergency_stop', sa.Boolean(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('autonomy_stopped', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('trust_level', sa.String(length=20), nullable=False),
    sa.Column('relationship', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('autonomy_enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_actions', sa.JSON(), nullable=False),
    sa.Column('forbidden_actions', sa.JSON(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('taken_over', sa.Boolean(), nullable=False),
    sa.Column('taken_over_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_handle'), 'contacts', ['handle'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('characters', sa.Integer(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('memory_item_id', sa.String(length=36), nullable=True),
    sa.Column('facts_extracted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_table('inbound_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_messages_dedupe_key'), 'inbound_messages', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_inbound_messages_handle'), 'inbound_messages', ['handle'], unique=False)
    op.create_index(op.f('ix_inbound_messages_next_attempt_at'), 'inbound_messages', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_inbound_messages_received_at'), 'inbound_messages', ['received_at'], unique=False)
    op.create_index(op.f('ix_inbound_messages_status'), 'inbound_messages', ['status'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_created_at'), 'insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_insights_key'), 'insights', ['key'], unique=True)
    op.create_index(op.f('ix_insights_severity'), 'insights', ['severity'], unique=False)
    op.create_index(op.f('ix_insights_status'), 'insights', ['status'], unique=False)
    op.create_table('job_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('match_notes', sa.Text(), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_applications_status'), 'job_applications', ['status'], unique=False)
    op.create_table('learning_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('draft', sa.Text(), nullable=False),
    sa.Column('final', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_events_kind'), 'learning_events', ['kind'], unique=False)
    op.create_table('learning_topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_topics_status'), 'learning_topics', ['status'], unique=False)
    op.create_table('memory_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('provenance', sa.String(length=300), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_items_memory_type'), 'memory_items', ['memory_type'], unique=False)
    op.create_table('model_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('task_class', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_usage_created_at'), 'model_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_usage_provider'), 'model_usage', ['provider'], unique=False)
    op.create_table('recruiter_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dimension', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_style_patterns_dimension'), 'style_patterns', ['dimension'], unique=False)
    op.create_index(op.f('ix_style_patterns_scope'), 'style_patterns', ['scope'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('autonomous_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('inbound_message_id', sa.String(length=36), nullable=True),
    sa.Column('incoming', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decision_reasons', sa.JSON(), nullable=False),
    sa.Column('autonomy_mode', sa.String(length=30), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_categories', sa.JSON(), nullable=False),
    sa.Column('communication_confidence', sa.Float(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('send_status', sa.String(length=20), nullable=False),
    sa.Column('send_error', sa.Text(), nullable=False),
    sa.Column('action_request_id', sa.String(length=36), nullable=True),
    sa.Column('user_reaction', sa.String(length=20), nullable=False),
    sa.Column('correction', sa.Text(), nullable=False),
    sa.Column('reacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('learning_event_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autonomous_responses_contact_id'), 'autonomous_responses', ['contact_id'], unique=False)
    op.create_index(op.f('ix_autonomous_responses_created_at'), 'autonomous_responses', ['created_at'], unique=False)
    op.create_index(op.f('ix_autonomous_responses_decision'), 'autonomous_responses', ['decision'], unique=False)
    op.create_index(op.f('ix_autonomous_responses_risk_level'), 'autonomous_responses', ['risk_level'], unique=False)
    op.create_index(op.f('ix_autonomous_responses_send_status'), 'autonomous_responses', ['send_status'], unique=False)
    op.create_index(op.f('ix_autonomous_responses_user_reaction'), 'autonomous_responses', ['user_reaction'], unique=False)
    op.create_table('document_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('quote', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('memory_item_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_facts_category'), 'document_facts', ['category'], unique=False)
    op.create_index(op.f('ix_document_facts_document_id'), 'document_facts', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_facts_status'), 'document_facts', ['status'], unique=False)
    op.create_table('memory_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', src.models.EmbeddingColumn(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['memory_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_chunks_item_id'), 'memory_chunks', ['item_id'], unique=False)
    op.create_table('message_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('incoming', sa.Text(), nullable=False),
    sa.Column('draft', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('final', sa.Text(), nullable=False),
    sa.Column('rationale', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_drafts_contact_id'), 'message_drafts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_message_drafts_status'), 'message_drafts', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('outbound_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('autonomous_response_id', sa.String(length=36), nullable=True),
    sa.Column('action_request_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_messages_contact_id'), 'outbound_messages', ['contact_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_created_at'), 'outbound_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbound_messages_handle'), 'outbound_messages', ['handle'], unique=False)
    op.create_index(op.f('ix_outbound_messages_status'), 'outbound_messages', ['status'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_messages_contact_id'), 'whatsapp_messages', ['contact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_messages_contact_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_outbound_messages_status'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_handle'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_created_at'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_contact_id'), table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_message_drafts_status'), table_name='message_drafts')
    op.drop_index(op.f('ix_message_drafts_contact_id'), table_name='message_drafts')
    op.drop_table('message_drafts')
    op.drop_index(op.f('ix_memory_chunks_item_id'), table_name='memory_chunks')
    op.drop_table('memory_chunks')
    op.drop_index(op.f('ix_document_facts_status'), table_name='document_facts')
    op.drop_index(op.f('ix_document_facts_document_id'), table_name='document_facts')
    op.drop_index(op.f('ix_document_facts_category'), table_name='document_facts')
    op.drop_table('document_facts')
    op.drop_index(op.f('ix_autonomous_responses_user_reaction'), table_name='autonomous_responses')
    op.drop_index(op.f('ix_autonomous_responses_send_status'), table_name='autonomous_responses')
    op.drop_index(op.f('ix_autonomous_responses_risk_level'), table_name='autonomous_responses')
    op.drop_index(op.f('ix_autonomous_responses_decision'), table_name='autonomous_responses')
    op.drop_index(op.f('ix_autonomous_responses_created_at'), table_name='autonomous_responses')
    op.drop_index(op.f('ix_autonomous_responses_contact_id'), table_name='autonomous_responses')
    op.drop_table('autonomous_responses')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_style_patterns_scope'), table_name='style_patterns')
    op.drop_index(op.f('ix_style_patterns_dimension'), table_name='style_patterns')
    op.drop_table('style_patterns')
    op.drop_table('recruiter_contacts')
    op.drop_index(op.f('ix_model_usage_provider'), table_name='model_usage')
    op.drop_index(op.f('ix_model_usage_created_at'), table_name='model_usage')
    op.drop_table('model_usage')
    op.drop_index(op.f('ix_memory_items_memory_type'), table_name='memory_items')
    op.drop_table('memory_items')
    op.drop_index(op.f('ix_learning_topics_status'), table_name='learning_topics')
    op.drop_table('learning_topics')
    op.drop_index(op.f('ix_learning_events_kind'), table_name='learning_events')
    op.drop_table('learning_events')
    op.drop_index(op.f('ix_job_applications_status'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_insights_status'), table_name='insights')
    op.drop_index(op.f('ix_insights_severity'), table_name='insights')
    op.drop_index(op.f('ix_insights_key'), table_name='insights')
    op.drop_index(op.f('ix_insights_created_at'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_inbound_messages_status'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_received_at'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_next_attempt_at'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_handle'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_dedupe_key'), table_name='inbound_messages')
    op.drop_table('inbound_messages')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_contacts_handle'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('autonomy_state')
    op.drop_index(op.f('ix_audit_events_action_request_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_action_requests_status'), table_name='action_requests')
    op.drop_table('action_requests')
    # ### end Alembic commands ###
