"""style samples carry an audience scope

Revision ID: 8da983278d91
Revises: 7c8da978d3a4
Create Date: 2026-08-17 12:02:01.079657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders ARIA's pgvector column as src.models.EmbeddingColumn(),
# so the module must be importable from every migration.
import src.models  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '8da983278d91'
down_revision: Union[str, Sequence[str], None] = '7c8da978d3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Adjusted from autogenerate, which proposed a NOT NULL column with no
    default. Postgres rejects that on a table with rows — the live table has
    them — so the column arrives with a server default instead.

    Existing style samples are backfilled to "global": they were pasted before
    scoping existed, offered as examples of how MORICE writes in general, and
    demoting them to an unknown audience would silently drop his voice from
    every draft.
    """
    op.add_column(
        'memory_items',
        sa.Column(
            'style_scope', sa.String(length=60), nullable=False, server_default=''
        ),
    )
    op.create_index(op.f('ix_memory_items_style_scope'), 'memory_items', ['style_scope'], unique=False)
    op.execute(
        "UPDATE memory_items SET style_scope = 'global' WHERE kind = 'style'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_items_style_scope'), table_name='memory_items')
    op.drop_column('memory_items', 'style_scope')
    # ### end Alembic commands ###
